package schema

import org.apache.spark.sql.types._

object ChicagoCollisionSchema {
  val schema: StructType = StructType(Array(
    StructField("CRASH_RECORD_ID", StringType, nullable = true),
    StructField("CRASH_DATE_EST_I", StringType, nullable = true),
    StructField("CRASH_DATE", StringType, nullable = true),
    StructField("POSTED_SPEED_LIMIT", IntegerType, nullable = true),
    StructField("TRAFFIC_CONTROL_DEVICE", StringType, nullable = true),
    StructField("DEVICE_CONDITION", StringType, nullable = true),
    StructField("WEATHER_CONDITION", StringType, nullable = true),
    StructField("LIGHTING_CONDITION", StringType, nullable = true),
    StructField("FIRST_CRASH_TYPE", StringType, nullable = true),
    StructField("TRAFFICWAY_TYPE", StringType, nullable = true),
    StructField("LANE_CNT", IntegerType, nullable = true),
    StructField("ALIGNMENT", StringType, nullable = true),
    StructField("ROADWAY_SURFACE_COND", StringType, nullable = true),
    StructField("ROAD_DEFECT", StringType, nullable = true),
    StructField("REPORT_TYPE", StringType, nullable = true),
    StructField("CRASH_TYPE", StringType, nullable = true),
    StructField("INTERSECTION_RELATED_I", StringType, nullable = true),
    StructField("NOT_RIGHT_OF_WAY_I", StringType, nullable = true),
    StructField("HIT_AND_RUN_I", StringType, nullable = true),
    StructField("DAMAGE", StringType, nullable = true),
    StructField("DATE_POLICE_NOTIFIED", StringType, nullable = true),
    StructField("PRIM_CONTRIBUTORY_CAUSE", StringType, nullable = true),
    StructField("SEC_CONTRIBUTORY_CAUSE", StringType, nullable = true),
    StructField("STREET_NO", IntegerType, nullable = true),
    StructField("STREET_DIRECTION", StringType, nullable = true),
    StructField("STREET_NAME", StringType, nullable = true),
    StructField("BEAT_OF_OCCURRENCE", StringType, nullable = true),
    StructField("PHOTOS_TAKEN_I", StringType, nullable = true),
    StructField("STATEMENTS_TAKEN_I", StringType, nullable = true),
    StructField("DOORING_I", StringType, nullable = true),
    StructField("WORK_ZONE_I", StringType, nullable = true),
    StructField("WORK_ZONE_TYPE", StringType, nullable = true),
    StructField("WORKERS_PRESENT_I", StringType, nullable = true),
    StructField("NUM_UNITS", IntegerType, nullable = true),
    StructField("MOST_SEVERE_INJURY", StringType, nullable = true),
    StructField("INJURIES_TOTAL", IntegerType, nullable = true),
    StructField("INJURIES_FATAL", IntegerType, nullable = true),
    StructField("INJURIES_INCAPACITATING", IntegerType, nullable = true),
    StructField("INJURIES_NON_INCAPACITATING", IntegerType, nullable = true),
    StructField("INJURIES_REPORTED_NOT_EVIDENT", IntegerType, nullable = true),
    StructField("INJURIES_NO_INDICATION", IntegerType, nullable = true),
    StructField("INJURIES_UNKNOWN", IntegerType, nullable = true),
    StructField("CRASH_HOUR", IntegerType, nullable = true),
    StructField("CRASH_DAY_OF_WEEK", IntegerType, nullable = true),
    StructField("CRASH_MONTH", IntegerType, nullable = true),
    StructField("LATITUDE", DoubleType, nullable = true),
    StructField("LONGITUDE", DoubleType, nullable = true),
    StructField("LOCATION", StringType, nullable = true)
  ))
}
